### ISSUE TITLE
[FEATURE] reduce app size

### ISSUE THREAD

**Issue by subframe7536** [Tohrusky/Final2x#108]
Thanks for your great work!

The electron app size can be optimized. there are plenty of useless npm dependencies be packaged into the app

According to https://github.com/electron-vite/vite-plugin-electron-renderer#dependency-pre-bundling and electron-builder doc, all the dependencies are bundled by vite and there is no need to package them into app.

The recommended approach is simply moving all the dependencies, except for native modules, from the `dependencies` to the `devDependencies` in the `package.json`.

**Comment by Tohrusky** [comment]
Hello @subframe7536, your issue has been closed because it does not conform to our issue template. 

你好 @subframe7536，为了能够进行高效沟通，我们对 issue 有一定的格式要求，你的 issue 因为不符合模版格式而被自动关闭。

こんにちは、@subframe7536さん、あなたの問題は、弊社の問題テンプレートに準拠していないため、クローズされました。

**Comment by Tohrusky** [comment]
Hello @subframe7536, your issue has been closed because it does not conform to our issue template. 

你好 @subframe7536，为了能够进行高效沟通，我们对 issue 有一定的格式要求，你的 issue 因为不符合模版格式而被自动关闭。

こんにちは、@subframe7536さん、あなたの問題は、弊社の問題テンプレートに準拠していないため、クローズされました。
