### ISSUE TITLE
[FEATURE] reduce app size

### ISSUE THREAD

**Issue by subframe7536** [Tohrusky/Final2x#109]
### Is your feature request related to a problem? | 你的feature请求是否与一个问题有关？ | あなたのfeatureリクエストは質問に関連していますか？
No

### Detail | 详细描述 | 詳細な説明

Thanks for your great work!

The electron app size can be optimized. there are plenty of useless npm dependencies be packaged into the app

According to https://github.com/electron-vite/vite-plugin-electron-renderer#dependency-pre-bundling and electron-builder doc, all the dependencies are bundled by vite and there is no need to package them into app.

The recommended approach is simply moving all the dependencies, except for native modules, from the `dependencies` to the `devDependencies` in the `package.json`.

**Comment by Tohrusky** [comment]
![306f22aab65ca04b9f0f2aa3633f76b5](https://github.com/Tohrusky/Final2x/assets/65994850/a7037c84-d602-461c-b18f-38f2fb4a84bf)

like these?  您可以为此提一个pr吗，我可能没理解正确

**Comment by subframe7536** [comment]
已提pr

**Comment by Tohrusky** [comment]
Hello @d-blanken, your issue has been closed because it has been inactive for a long time.

你好 @d-blanken，你的 issue 因为长时间不活跃而被自动关闭。

こんにちは、@d-blankenさん、お問い合わせは長期間活動がないため、閉じられました。

**Comment by d-blanken** [comment]
Hello Tohrusky, I never mentioned something like this.
