### ISSUE TITLE
[FEATURE]提供个dockerfile吧，环境安装各种报错

### ISSUE THREAD

**Issue by zuoyangs** [Tohrusky/Final2x#111]

**Comment by Tohrusky** [comment]
这是gui应用啊，打docker有什么必要。再说环境很难装吗？Deb/Ubuntu Arch 都挺正常的。
https://final2x.tohru.top/zh/pages/guide/install.html

**Comment by zuoyangs** [comment]
> 这是gui应用啊，打docker有什么必要。再说环境很难装吗？Deb/Ubuntu Arch 都挺正常的。 https://final2x.tohru.top/zh/pages/guide/install.html

我还以为是web，在 python docker 里安装一直报错，说缺少各种依赖包。GUI，我在pc win电脑上试试

**Comment by Tohrusky** [comment]
https://final2x.tohru.top/zh/pages/python/
也提供了命令行/库

**Comment by zuoyangs** [comment]
> > Bot detected the issue body's language is not English, translate it automatically.
> 
> https://final2x.tohru.top/zh/pages/python/ Also provides the command line/library

thanks

**Comment by zuoyangs** [comment]
> https://final2x.tohru.top/zh/pages/python/ 也提供了命令行/库

![image](https://github.com/Tohrusky/Final2x/assets/56719243/fc2b9d43-de2a-4d48-ba6d-3f0edb934693)
win安装是很简单，一条命令搞定

**Comment by Tohrusky** [comment]
![image](https://github.com/Tohrusky/Final2x/assets/65994850/2d7d1212-3639-487b-a64f-812d448e709f)
