### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by yenkeyy** [Tohrusky/Final2x#17]
### Describe the bug | 描述错误 | BUGの説明

arm64的dmg，在macos 13.4.1安装后点击打开，弹窗app文件损坏无法打开，移到废纸篓。

### To reproduce | 复现步骤 | 再現方法 
3. See error

### Context | 运行环境 | バックグラウンド
 - OS: [e.g. Ubuntu 20.04]
 - Arch: [e.g. x64]

### Error log | 报错日志 | ログ
```shell
your error log
```

### Additional context | 附加内容 | 追加コンテキスト
Add any other context and screenshots to help explain your problem.

**Comment by Tohrusky** [comment]
MacOS
```
sudo spctl --master-disable
# Disable Gatekeeper, then allow applications downloaded from anywhere in System Preferences > Security & Privacy > General
xattr -cr /Applications/Final2x.app
```
In first time, you need to run the command above in terminal to allow the app to run, and first process may very slow because of Apple's Check.
