### ISSUE TITLE
[Bug] Failed to execute

### ISSUE THREAD

**Issue by d-blanken** [Tohrusky/Final2x#170]
### Please carefully review each item in the checklist below | 请认真检查以下清单中的每一项 | 以下のチェックリストの各項目を注意深く確認してください

- [X] Searched and didn't find a similar issue | 已经搜索过，没有发现类似issue | 類似の問題が見つかりませんでした
- [X] Searched documentation and didn't find relevant content | 已经搜索过文档，没有发现相关内容 | ドキュメントを検索して関連する内容が見つかりませんでした
- [X] Tried with the latest version and the issue still exists | 已经尝试使用过最新版，问题依旧存在 | 最新バージョンを試しましたが問題は解消されませんでした

### Software Version | 软件版本 | ソフトウェアバージョン

1.1.5

### Operating System | 操作系统 | オペレーティングシステム

Windows x64

### System Version | 系统版本 | システムバージョン

Windows 10 Pro 22H2

### Describe the bug | 描述错误 | BUGの説明

Short after start program stop with Pocessing failed.

### To reproduce | 复现步骤 | 再現方法

3. See error

### Error log | 报错日志 | ログ

[final2x_problem.docx](https://github.com/Tohrusky/Final2x/files/12623108/final2x_problem.docx)

### Additional context | 附加内容 | 追加コンテキスト

Could it be that my GT 610 ist too old?

**Comment by Tohrusky** [comment]
https://final2x.tohru.top/pages/guide/use.html
gt610 is not support vulkan, you should try cpu mode…

**Comment by Tohrusky** [comment]
https://github.com/Tohrusky/Final2x/pull/171
mention ya in other issues is a bug 😂, I have fixed it

**Comment by d-blanken** [comment]
Thank You. Cpu mode instead of Auto works.
Can be closed.
