### ISSUE TITLE
[FEATURE] Add software screenshots to readme.md

### ISSUE THREAD

**Issue by samlach2222** [Tohrusky/Final2x#174]
### Please carefully review each item in the checklist below | 请认真检查以下清单中的每一项 | 以下のチェックリストの各項目を注意深く確認してください

- [X] Searched and didn't find a similar issue | 已经搜索过，没有发现类似issue | 類似の問題が見つかりませんでした

### Is your feature request related to a problem? | 你的feature请求是否与一个问题有关？ | あなたのfeatureリクエストは質問に関連していますか？

I really love Final2x UI, and I think adding screenshots will allow you to have more user interested by it, because some users are looking for Waifu2x app with a good UI (and here it's a really good one). I almost didn't use Final2x because of the lack of UI screenshots.

### Detail | 详细描述 | 詳細な説明

Adding UI screenshots to README.md

**Comment by Tohrusky** [comment]
Thanks! Done in https://github.com/Tohrusky/Final2x/pull/180
