### ISSUE TITLE
[FEATURE] (CLI) Command Line Interface support

### ISSUE THREAD

**Issue by MarcG2** [Tohrusky/Final2x#179]
### Please carefully review each item in the checklist below | 请认真检查以下清单中的每一项 | 以下のチェックリストの各項目を注意深く確認してください

- [X] Searched and didn't find a similar issue | 已经搜索过，没有发现类似issue | 類似の問題が見つかりませんでした

### Is your feature request related to a problem? | 你的feature请求是否与一个问题有关？ | あなたのfeatureリクエストは質問に関連していますか？

Final2X lacks a CLI.

### Detail | 详细描述 | 詳細な説明

A command line interface for this tool would be a nice addition. I was hoping to incorporate Final2X into my custom image processing tool set.  But without a CLI, that's not possible.

**Comment by Tohrusky** [comment]
https://github.com/Tohrusky/Final2x-core
https://final2x.tohru.top/pages/python/

**Comment by MarcG2** [comment]
Thanks, that explains it.  The CLI version is kept in a separate Github project.   
Googling "Final2X command line" is surprisingly ineffective.
