### ISSUE TITLE
[FEATURE] Final2x CORE.  Add option to disable opening output folder

### ISSUE THREAD

**Issue by MarcG2** [Tohrusky/Final2x#191]
### Please carefully review each item in the checklist below | 请认真检查以下清单中的每一项 | 以下のチェックリストの各項目を注意深く確認してください

- [x] Searched and didn't find a similar issue | 已经搜索过，没有发现类似issue | 類似の問題が見つかりませんでした

### Is your feature request related to a problem? | 你的feature请求是否与一个问题有关？ | あなたのfeatureリクエストは質問に関連していますか？

Final2x-core opens the output directory after running.  This behavior is very undesirable in some cases.  If running multiple instances in parallel, Final2x-core will repeatedly try to open the same folder, resulting in many Windows errors.

Please add an option to disable this behavior.

### Detail | 详细描述 | 詳細な説明

Please add an option to disable opening the "outputs" folder.

**Comment by Tohrusky** [comment]
Hello! your issue has been closed because it has been inactive for a long time.

你好，你的 issue 因为长时间不活跃而被自动关闭。

こんにちは、お問い合わせは長期間活動がないため、閉じられました。

**Comment by MHillier98** [comment]
I'd like this feature :)

**Comment by Tohrusky** [comment]
download ci build here https://github.com/Tohrusky/Final2x/actions/runs/10995398923
