### ISSUE TITLE
Feature Request: Please support Face Restoration. 

### ISSUE THREAD

**Issue by RockySteveJobs** [Tohrusky/Final2x#22]
Please support Face Restoration, it will be more useful.
[https://github.com/TencentARC/GFPGAN](https://github.com/TencentARC/GFPGAN)
![image](https://github.com/Tohrusky/Final2x/assets/7598630/2c250696-ba58-4030-86d1-b6820e232eb9)

**Comment by Tohrusky** [comment]
Hello @RockySteveJobs, your issue has been closed because it does not conform to our issue template. 

你好 @RockySteveJobs，为了能够进行高效沟通，我们对 issue 有一定的格式要求，你的 issue 因为不符合模版格式而被自动关闭。

こんにちは、@RockySteveJobsさん、あなたの問題は、弊社の問題テンプレートに準拠していないため、クローズされました。

**Comment by Tohrusky** [comment]
Hello @RockySteveJobs, your issue has been closed because because the title does not conform to our specification.

你好 @RockySteveJobs，为了能够进行高效沟通，我们对 issue 有一定的格式要求，你的 issue 因为标题不符合规范而被自动关闭。

こんにちは、@RockySteveJobsさん、タイトルが仕様に準拠していないため、ご提案いただいた問題はクローズされました。
