### ISSUE TITLE
[FEATURE] GIF support 

### ISSUE THREAD

**Issue by VvvvvGH** [Tohrusky/Final2x#24]
### Detail | 详细描述 | 詳細な説明
请问可以放大 GIF 吗？ 
### Additional context | 附加内容 | 追加コンテキスト
可以通过将 GIF 拆分为多张图片，分别对图片放大，最后合并成 GIF 文件

**Comment by Tohrusky** [comment]
Hello @VvvvvGH, your issue has been closed because it does not conform to our issue template. 

你好 @VvvvvGH，为了能够进行高效沟通，我们对 issue 有一定的格式要求，你的 issue 因为不符合模版格式而被自动关闭。

こんにちは、@VvvvvGHさん、あなたの問題は、弊社の問題テンプレートに準拠していないため、クローズされました。
