### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by WySen-Yeah** [Tohrusky/Final2x#241]
### Please carefully review each item in the checklist below | 请认真检查以下清单中的每一项 | 以下のチェックリストの各項目を注意深く確認してください

- [X] Searched and didn't find a similar issue | 已经搜索过，没有发现类似issue | 類似の問題が見つかりませんでした

### Is your feature request related to a problem? | 你的feature请求是否与一个问题有关？ | あなたのfeatureリクエストは質問に関連していますか？

Windows安装版强制安装在系统盘，无法更改安装位置

### Detail | 详细描述 | 詳細な説明

添加安装位置选择功能

**Comment by Tohrusky** [comment]
Hello @WySen-Yeah, your issue has been closed because the title does not conform to our specification.

你好 @WySen-Yeah，为了能够进行高效沟通，我们对 issue 有一定的格式要求，你的 issue 因为标题不符合规范而被自动关闭。

こんにちは、@WySen-Yeahさん、タイトルが仕様に準拠していないため、ご提案いただいた問題はクローズされました。
