### ISSUE TITLE
[FEATURE] 功能反馈

### ISSUE THREAD

**Issue by WySen-Yeah** [Tohrusky/Final2x#242]
### Please carefully review each item in the checklist below | 请认真检查以下清单中的每一项 | 以下のチェックリストの各項目を注意深く確認してください

- [x] Searched and didn't find a similar issue | 已经搜索过，没有发现类似issue | 類似の問題が見つかりませんでした

### Is your feature request related to a problem? | 你的feature请求是否与一个问题有关？ | あなたのfeatureリクエストは質問に関連していますか？

1. Windows安装版没有自由选择安装位置的功能，会强制安装在系统盘
2. 对于不清楚各种模型作用与偏向性的用户，门槛较高，不方便用户使用
3. 输入目录强制要求添加outputs文件夹，不方便使用
4. 优化后的图片文件体积大幅增大，存在大量冗余重复数据，占用大量空间，存储空间浪费严重

### Detail | 详细描述 | 詳細な説明

1. 为安装版添加自由更改安装位置功能
2. 修改模型名称为其模型作用，如：动漫模型，真人模型，景物模型等
3. 强烈要求修改输出目录为文件原路径
4. 强烈要求添加无损压缩功能或低损压缩功能（支持透明图片压缩），在图片优化之后进行体积压缩

### Additional context | 附加内容 | 追加コンテキスト

无

**Comment by hyw-dev** [comment]
very humorous，lmao

**Comment by WySen-Yeah** [comment]
不想优化就算了，反正替补产品有很多，爱改不改

**Comment by JLCJ204** [comment]
白嫖且狗叫66

**Comment by WySen-Yeah** [comment]
> 白嫖且狗叫66

你是个什么东西？在这狗叫？属疯狗的吗，见人就咬，老子支持过的正版东西多了，老子用的软件，玩的游戏，什么的都是买的正版的，你有什么资格在这个狗叫，你叫你妈呢？你支持过什么东西？狗娘养的东西，自己嫖着，来骂别人白嫖，你是什么东西？你缺钱吗？跪下来求求老子，老子可以考虑给你几毛钱，然后还可以给你安排挑大粪的工作，你知道什么叫做开源吗？既然开源了，那就不是强制付费的，谁都可以用，愿不愿意支持完全看别人心情，就算我真的白嫖又能怎样？如果这个软件做的确实比较好用，我肯定来支持，最好出个付费买断的，现在倒好呀，老子来提个意见，一个两个疯狗追着我咬，第一次见这种人，真牛逼

**Comment by WySen-Yeah** [comment]
真恶心

**Comment by JLCJ204** [comment]
不想优化就算了，反正替补产品有很多,爱改不改

**Comment by Yountenn** [comment]
very humorous，lmao
