### ISSUE TITLE
[FEATURE] Custom Width

### ISSUE THREAD

**Issue by njardim** [Tohrusky/Final2x#368]
### Please carefully review each item in the checklist below | 请认真检查以下清单中的每一项 | 以下のチェックリストの各項目を注意深く確認してください

- [X] Searched and didn't find a similar issue | 已经搜索过，没有发现类似issue | 類似の問題が見つかりませんでした

### Is your feature request related to a problem? | 你的feature请求是否与一个问题有关？ | あなたのfeatureリクエストは質問に関連していますか？

First of all, congratulations on a great program! Keep up the good work.

I would like to request a new custom feature, and it's the ability to also specify the final Custom Width of an image instead of just relying on the current Model Scale, or Custom Scale Factor to upscale images.

### Detail | 详细描述 | 詳細な説明

This is important because if we are batch upscaling hundreds of images with different sizes from a folder, and we need to normalize the final width for all images, let's say to 3840px, then with the current Model Scale, or Custom Scale Factor, all images are upscaled relative to their original image size, and what we need is to upscale all images to a specific width, no matter the original image size. The height of all images should be adjusted automatically based on the specified custom width. 

This allows a greater degree of flexibility while upscaling images.

Thank you.

**Comment by Tohrusky** [comment]
Hello! your issue has been closed because it has been inactive for a long time.

你好，你的 issue 因为长时间不活跃而被自动关闭。

こんにちは、お問い合わせは長期間活動がないため、閉じられました。
