### ISSUE TITLE
[BUG] 無法找到 GPU

### ISSUE THREAD

**Issue by puBadBad** [Tohrusky/Final2x#37]
### Describe the bug | 描述错误 | BUGの説明
僅有 CPU 的選項
![image](https://github.com/Tohrusky/Final2x/assets/128451053/5a77871d-e6b5-43a2-aaa3-6b871574c0d9)

### Context | 运行环境 | バックグラウンド
windows11 x64

**Comment by Tohrusky** [comment]
https://github.com/Tohrusky/Final2x/commit/e11d22da53241c7895ef0b45d96a97fbdadf1ec8

虽然没检测到gpu，大概率驱动是有问题的，但还是加了强行指定gpu
