### ISSUE TITLE
Finalx2

### ISSUE THREAD

**Issue by Farzanafshar** [Tohrusky/Final2x#38]

**Comment by Tohrusky** [comment]
Hello @Farzanafshar, your issue has been closed because the title does not conform to our specification.

你好 @Farzanafshar，为了能够进行高效沟通，我们对 issue 有一定的格式要求，你的 issue 因为标题不符合规范而被自动关闭。

こんにちは、@Farzanafsharさん、タイトルが仕様に準拠していないため、ご提案いただいた問題はクローズされました。

**Comment by Tohrusky** [comment]
Hello @Farzanafshar, your issue has been closed because it does not conform to our issue template. 

你好 @Farzanafshar，为了能够进行高效沟通，我们对 issue 有一定的格式要求，你的 issue 因为不符合模版格式而被自动关闭。

こんにちは、@Farzanafsharさん、あなたの問題は、弊社の問題テンプレートに準拠していないため、クローズされました。
