### ISSUE TITLE
[Bug] Application is damaged on Mac ARM64

### ISSUE THREAD

**Issue by Zvirovyi** [Tohrusky/Final2x#405]
### Please carefully review each item in the checklist below | 请认真检查以下清单中的每一项 | 以下のチェックリストの各項目を注意深く確認してください

- [X] Searched and didn't find a similar issue | 已经搜索过，没有发现类似issue | 類似の問題が見つかりませんでした
- [X] Searched documentation and didn't find relevant content | 已经搜索过文档，没有发现相关内容 | ドキュメントを検索して関連する内容が見つかりませんでした
- [X] Tried with the latest version and the issue still exists | 已经尝试使用过最新版，问题依旧存在 | 最新バージョンを試しましたが問題は解消されませんでした

### Software Version | 软件版本 | ソフトウェアバージョン

1.2.0, 1.1.5, 1.0.2, beta

### Operating System | 操作系统 | オペレーティングシステム

macOS arm64 (M1,M2...)

### System Version | 系统版本 | システムバージョン

Mac Os Sonoma 14.4.1

### Describe the bug | 描述错误 | BUGの説明

Can't open arm64 version on Macbook Air M1, it says 'Application is damaged'. Intel x64 version opens just fine

### To reproduce | 复现步骤 | 再現方法

1. Download any macOS ARM64 release (dmg / unpacked)
2. Try to open it
3. See error

### Error log | 报错日志 | ログ

_There is no log as application doesn't open_

**Comment by Tohrusky** [comment]
my dev env is Sonoma 14.4.1 too, try `xattr -cr /Applications/Final2x.app`
https://github.com/Tohrusky/Final2x#macos

**Comment by Tohrusky** [comment]
Hello! your issue has been closed because it has been inactive for a long time.

你好，你的 issue 因为长时间不活跃而被自动关闭。

こんにちは、お問い合わせは長期間活動がないため、閉じられました。
