### ISSUE TITLE
How to call it through the command line?

### ISSUE THREAD

**Issue by lexluthors** [Tohrusky/Final2x#406]
### Please carefully review each item in the checklist below | 请认真检查以下清单中的每一项 | 以下のチェックリストの各項目を注意深く確認してください

- [ ] Searched and didn't find a similar issue | 已经搜索过，没有发现类似issue | 類似の問題が見つかりませんでした

### Is your feature request related to a problem? | 你的feature请求是否与一个问题有关？ | あなたのfeatureリクエストは質問に関連していますか？

How to call it through the command line?

### Detail | 详细描述 | 詳細な説明

How to call it through the command line?

**Comment by Tohrusky** [comment]
Hello @lexluthors, your issue has been closed because the title does not conform to our specification.

你好 @lexluthors，为了能够进行高效沟通，我们对 issue 有一定的格式要求，你的 issue 因为标题不符合规范而被自动关闭。

こんにちは、@lexluthorsさん、タイトルが仕様に準拠していないため、ご提案いただいた問題はクローズされました。
