### ISSUE TITLE
[Bug] Bad CPU type in executable

### ISSUE THREAD

**Issue by b0gdanw** [Tohrusky/Final2x#502]
### Please carefully review each item in the checklist below | 请认真检查以下清单中的每一项 | 以下のチェックリストの各項目を注意深く確認してください

- [X] Searched and didn't find a similar issue | 已经搜索过，没有发现类似issue | 類似の問題が見つかりませんでした
- [X] Searched documentation and didn't find relevant content | 已经搜索过文档，没有发现相关内容 | ドキュメントを検索して関連する内容が見つかりませんでした
- [X] Tried with the latest version and the issue still exists | 已经尝试使用过最新版，问题依旧存在 | 最新バージョンを試しましたが問題は解消されませんでした

### Software Version | 软件版本 | ソフトウェアバージョン

v1.3.0

### Operating System | 操作系统 | オペレーティングシステム

macOS x64 (Intel)

### System Version | 系统版本 | システムバージョン

12.7.5 (21H1222)

### Describe the bug | 描述错误 | BUGの説明

For Final2x-macos-x64-dmg.dmg, Final2x.app/Contents/Resources/app/resources/Final2x-core/Final2x-core is only Mach-O 64-bit executable **arm64**. 
That leads to "/Applications/Final2x.app/Contents/Resources/app/resources/Final2x-core/Final2x-core: Bad CPU type in executable CLOSE CODE:126"

### To reproduce | 复现步骤 | 再現方法

1. Load image
2. Click start
3. Read log

### Error log | 报错日志 | ログ

```
/bin/sh: /Applications/Final2x.app/Contents/Resources/app/resources/Final2x-core/Final2x-core: Bad CPU type in executable
CLOSE CODE:126
```

### Additional context | 附加内容 | 追加コンテキスト

v1.2.0 works on Intel (Final2x-macos-x64-dmg.dmg))

**Comment by Tohrusky** [comment]
![16d50ac88003df8aec6f8438c320b5d3](https://github.com/Tohrusky/Final2x/assets/65994850/d7b4d6e4-e138-422f-b587-49d7c6a8861c)
oh! now github actions support macOS arm
deafult is arm, let me release again later

**Comment by Tohrusky** [comment]
https://github.com/Tohrusky/Final2x/pull/503
