### ISSUE TITLE
[Bug]  任务管理器GPU和设置GPU序号不对

### ISSUE THREAD

**Issue by liwejqw** [Tohrusky/Final2x#524]
### Please carefully review each item in the checklist below | 请认真检查以下清单中的每一项 | 以下のチェックリストの各項目を注意深く確認してください

- [X] Searched and didn't find a similar issue | 已经搜索过，没有发现类似issue | 類似の問題が見つかりませんでした
- [X] Searched documentation and didn't find relevant content | 已经搜索过文档，没有发现相关内容 | ドキュメントを検索して関連する内容が見つかりませんでした
- [X] Tried with the latest version and the issue still exists | 已经尝试使用过最新版，问题依旧存在 | 最新バージョンを試しましたが問題は解消されませんでした

### Software Version | 软件版本 | ソフトウェアバージョン

1.3.1

### Operating System | 操作系统 | オペレーティングシステム

Windows x64

### System Version | 系统版本 | システムバージョン

Windows 11 专业版 23H2

### Describe the bug | 描述错误 | BUGの説明

任务管理器GPU和设置GPU序号不对
{The task manager GPU and setting GPU serial number are incorrect}

### To reproduce | 复现步骤 | 再現方法

安装软件或者配置软件后，清除gpu驱动，重新安装后就会出现了.
{After installing or configuring the software, clearing the GPU driver and reinstalling it will cause an error}

### Error log | 报错日志 | ログ

no

### Additional context | 附加内容 | 追加コンテキスト

![I7L2J(GJ2WM_} 4IE8W(4HV](https://github.com/user-attachments/assets/65d9a53b-eea0-4a63-9530-2ac8077f62c8)
![LW8MZ4KR @J$}Q3AQ}Q(KEG](https://github.com/user-attachments/assets/fcd840ff-111a-4f91-b9d6-e75cbfbc93cc)
![LW8MZ4KR @J$}Q3AQ}Q(KEG](https://github.com/user-attachments/assets/80ed5f31-dc6e-4afa-b3d1-4d28cd6fef0a)

**Comment by Tohrusky** [comment]
这个确实暂时没啥好办法，你用Auto默认就是第一个GPU

**Comment by Tohrusky** [comment]
新版本改用PyTorch了 以后不用选id 默认Auto就行
