### ISSUE TITLE
[Bug] Windows图片位于磁盘根目录下，输出目录的路径异常，导致某些磁盘无法正常存放输出文件

### ISSUE THREAD

**Issue by XY0797** [Tohrusky/Final2x#597]
### Please carefully review each item in the checklist below | 请认真检查以下清单中的每一项 | 以下のチェックリストの各項目を注意深く確認してください

- [X] Searched and didn't find a similar issue | 已经搜索过，没有发现类似issue | 類似の問題が見つかりませんでした
- [X] Searched documentation and didn't find relevant content | 已经搜索过文档，没有发现相关内容 | ドキュメントを検索して関連する内容が見つかりませんでした
- [X] Tried with the latest version and the issue still exists | 已经尝试使用过最新版，问题依旧存在 | 最新バージョンを試しましたが問題は解消されませんでした

### Software Version | 软件版本 | ソフトウェアバージョン

1.3.2

### Operating System | 操作系统 | オペレーティングシステム

Windows x64

### System Version | 系统版本 | システムバージョン

Windows 11

### Describe the bug | 描述错误 | BUGの説明

![image](https://github.com/user-attachments/assets/4e967de0-bb14-457b-a5bc-227378e26a6a)

如图所示，这种目录是不符合规范的，在某些硬盘上会导致出错

### To reproduce | 复现步骤 | 再現方法

1. 准备一张图片，放到某个盘的根目录下
2. 使用本软件超分
3. 错误即可复现

### Error log | 报错日志 | ログ

```
2024-11-01 00:34:47.060 | SUCCESS  | Final2x_core.src.SRqueue:SR_queue:83 - ______Process_Completed______: R:\2.jpg
2024-11-01 00:34:47.113 | SUCCESS  | __main__:main:81 - ______SR_COMPLETED______
2024-11-01 00:34:47.126 | ERROR    | __main__:open_folder:49 - [WinError 2] ϵͳ�Ҳ���ָ�����ļ���: 'R:outputs'
2024-11-01 00:34:47.126 | ERROR    | __main__:open_folder:50 - cannot open output folder
```

### Additional context | 附加内容 | 追加コンテキスト

测试在内存盘内进行，但是后续把软件和图片都移动到SSD硬盘，也能复现路径的异常。
但是在我SSD里面，这种错误的路径是能被正常解析识别的，可以正常的创建文件夹和写出文件。
所以说此BUG可能影响内存盘、虚拟磁盘、网络驱动器等特殊硬盘，对普通硬盘影响不大。

**Comment by lattaai1** [comment]
Hello, I've fixed this issue!

This is what I've done:
I've identified the issue with the output path handling for special disk types like RAM disks, virtual disks, and network drives. The problem occurs because the current implementation doesn't properly handle root directory paths. I've made changes to the `getOutPutPATH` function in `getFinal2xconfig.ts` to ensure it correctly handles these cases.

I also created pull request: https://github.com/Tohrusky/Final2x/pull/598


> [!CAUTION]  
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

**Comment by Tohrusky** [comment]
现在这ai还能自动pr了？哈人 你看看他修的 ci build 可以吗

**Comment by Tohrusky** [comment]
看起来是不行的hh  bug发生在python侧

**Comment by Tohrusky** [comment]
打个断点看看这呢，文件夹没创建出来吗
https://github.com/Final2x/Final2x-core/blob/main/src/Final2x_core/src/SRqueue.py#L19

**Comment by XY0797** [comment]
> 打个断点看看这呢，文件夹没创建出来吗 https://github.com/Final2x/Final2x-core/blob/main/src/Final2x_core/src/SRqueue.py#L19

这个问题是出在路径选取。
R:\1.jpg
R:outputs
很明显“:”后面得有个\
这个bug只影响特殊驱动器，比如说虚拟磁盘等，它们严格要求路径得符合规范。
正常硬盘哪怕文件夹路径有这个问题，也会自动忽略，文件夹能创建成功的。

**Comment by Tohrusky** [comment]
> 
> 这个问题是出在路径选取。 R:\1.jpg R:outputs 很明显“:”后面得有个`\` 

我是说 `output_path: Path = Path(config.outputpath) / "outputs"` ，它这里创建出的目录是 R:/outputs 还是什么

我不熟悉windows，不过试了下可以处理挂载的磁盘里的图片，用内存盘是有什么特殊需求吗

此外请给全log，我还得看看是不是前端传过去的路径不对

**Comment by Tohrusky** [comment]
手动设置一下输出目录吧 应该可以避免这个问题
