### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by liofeu** [Tohrusky/Final2x#604]
### Please carefully review each item in the checklist below | 请认真检查以下清单中的每一项 | 以下のチェックリストの各項目を注意深く確認してください

- [ ] Searched and didn't find a similar issue | 已经搜索过，没有发现类似issue | 類似の問題が見つかりませんでした
- [ ] Searched documentation and didn't find relevant content | 已经搜索过文档，没有发现相关内容 | ドキュメントを検索して関連する内容が見つかりませんでした
- [ ] Tried with the latest version and the issue still exists | 已经尝试使用过最新版，问题依旧存在 | 最新バージョンを試しましたが問題は解消されませんでした

### Software Version | 软件版本 | ソフトウェアバージョン

2.0.0

### Operating System | 操作系统 | オペレーティングシステム

macOS x64 (Intel)

### System Version | 系统版本 | システムバージョン

10.15.7

### Describe the bug | 描述错误 | BUGの説明

You should give a minimum configuration in the readme, as I was able to install the 2.0.0 on a macOS 10.15 but when I runned an image superresolution, I got an error which says that a file (libvmaf.3.dylib) was built for Mac OS X 12.0.

### To reproduce | 复现步骤 | 再現方法

Install 2.0.0 on a macOS < 12.0
Start an image superresolution

### Error log | 报错日志 | ログ

```
0%
Click or drag and drop images or folders here to upload
diarization_lq.png

Log
{"pretrained_model_name":"RealESRGAN_RealESRGAN_x2plus_2x.pth","device":"auto","gh_proxy":null,"target_scale":null,"output_path":"/Users/lionel/Downloads","input_path":["/Users/lionel/Downloads/diarization_lq.png"]}
OPEN OUTPUT FOLDER: true
Traceback (most recent call last):
File "Final2x_core/__main__.py", line 8, in <module>
File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
File "Final2x_core/__init__.py", line 1, in <module>
'''
^^^^
File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
File "Final2x_core/SRqueue.py", line 4, in <module>
File "/Applications/Final2x.app/Contents/Resources/app/resources/Final2x-core/_internal/cv2/__init__.py", line 181, in <module>
bootstrap()
File "/Applications/Final2x.app/Contents/Resources/app/resources/Final2x-core/_internal/cv2/__init__.py", line 153, in bootstrap
native_module = importlib.import_module("cv2")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "importlib/__init__.py", line 126, in import_module
if sys.path[0] == BASE_DIR or os.path.realpath(sys.path[0]) == BASE_DIR:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: dlopen(/Applications/Final2x.app/Contents/Resources/app/resources/Final2x-core/_internal/cv2/cv2.abi3.so, 2): Symbol not found: __ZNSt3__113basic_filebufIcNS_11char_traitsIcEEE4openEPKcj
Referenced from: /Applications/Final2x.app/Contents/Resources/app/resources/Final2x-core/_internal/cv2/.dylibs/../../libvmaf.3.dylib (which was built for Mac OS X 12.0)
Expected in: /usr/lib/libc++.1.dylib
[6370] Failed to execute script '__main__' due to unhandled exception!
CLOSE CODE:1
```

**Comment by Tohrusky** [comment]
Hello @liofeu, your issue has been closed because the title does not conform to our specification.

你好 @liofeu，为了能够进行高效沟通，我们对 issue 有一定的格式要求，你的 issue 因为标题不符合规范而被自动关闭。

こんにちは、@liofeuさん、タイトルが仕様に準拠していないため、ご提案いただいた問題はクローズされました。
