### ISSUE TITLE
[FEATURE] 能否为每个模型添加一个简单说明，或者在release页面添加也行

### ISSUE THREAD

**Issue by s1805948721** [Tohrusky/Final2x#605]
### Please carefully review each item in the checklist below | 请认真检查以下清单中的每一项 | 以下のチェックリストの各項目を注意深く確認してください

- [X] Searched and didn't find a similar issue | 已经搜索过，没有发现类似issue | 類似の問題が見つかりませんでした

### Is your feature request related to a problem? | 你的feature请求是否与一个问题有关？ | あなたのfeatureリクエストは質問に関連していますか？

希望能够为每个模型添加一个简单说明，或者在release页面添加也行

### Detail | 详细描述 | 詳細な説明

希望能够为每个模型添加一个简单说明（特别是新模型的特点），或者在release页面添加也行

**Comment by Tohrusky** [comment]
太多了，模型未来还会继续增加，这部分是依赖[上游库](https://github.com/TensoRaws/ccrestoration)做的 code gen
不过大体可以分为动漫/非动漫，未来发release增加新模型确实可以说明一下，贴下原实现的repo

**Comment by s1805948721** [comment]
> 太多了，模型未来还会继续增加，这部分是依赖[上游库](https://github.com/TensoRaws/ccrestoration)做的 code gen 不过大体可以分为动漫/非动漫，未来发release增加新模型确实可以说明一下，贴下原实现的repo

ok,谢谢大大
