### ISSUE TITLE
[FEATURE]请求对视频处理的支持

### ISSUE THREAD

**Issue by win10ogod** [Tohrusky/Final2x#65]
### Is your feature request related to a problem? | 你的feature请求是否与一个问题有关？ | あなたのfeatureリクエストは質問に関連していますか？

与现有问题无关
### Detail | 详细描述 | 詳細な説明

请求对视频处理的支持
### Additional context | 附加内容 | 追加コンテキスト

此程序无法处理频视频，需要拆帧后小批量处理，但视频的帧率满高的不方便

**Comment by Tohrusky** [comment]
https://store.steampowered.com/app/1692080/SVFI
暂时没有这方面的考虑，有需要可以看看这个
