### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by pq9420** [Tohrusky/Final2x#71]

**Comment by Tohrusky** [comment]
Hello @pq9420, your issue has been closed because the title does not conform to our specification.

你好 @pq9420，为了能够进行高效沟通，我们对 issue 有一定的格式要求，你的 issue 因为标题不符合规范而被自动关闭。

こんにちは、@pq9420さん、タイトルが仕様に準拠していないため、ご提案いただいた問題はクローズされました。

**Comment by Tohrusky** [comment]
Hello @pq9420, your issue has been closed because the title does not conform to our specification.

你好 @pq9420，为了能够进行高效沟通，我们对 issue 有一定的格式要求，你的 issue 因为标题不符合规范而被自动关闭。

こんにちは、@pq9420さん、タイトルが仕様に準拠していないため、ご提案いただいた問題はクローズされました。
