### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by pq9420** [Tohrusky/Final2x#72]
### Describe the bug | 描述错误 | BUGの説明
处理了一张图片后就这样报错了，请问大佬是什么问题？

### Context | 运行环境 | バックグラウンド
操作系统及环境：w处理器:lntel(R) Core(TM) i7-8700K CPU @3.70GHz 3.70 GHz
已安装的内存(RAM): 8.00 GB (7.86 GB可用)
系统类型:64位操作系统，基于x64的处理器

### Error log | 报错日志 | ログ
Describe the bug | 描述错误 | BUGの説明
Log
[{"label":"CPU: Core™ i7-8700K","value":-1},{"label":"GPU 0: NVIDIA GeForce RTX 2060","value":0},{"label":"GPU 1: Intel(R) UHD Graphics 630","value":1},{"label":"GPU: Auto","value":114514}]
{"gpuid":0,"inputpath":["F:\1临时文件\final2x\final2x\2 (4).png"],"model":"RealESRGAN","modelscale":4,"modelnoise":0,"outputpath":"F:\1临时文件\final2x\final2x","targetscale":0,"tta":false}
ϵͳ�Ҳ���ָ����·����
CLOSE CODE:1

**Comment by Tohrusky** [comment]
Hello @pq9420, your issue has been closed because the title does not conform to our specification.

你好 @pq9420，为了能够进行高效沟通，我们对 issue 有一定的格式要求，你的 issue 因为标题不符合规范而被自动关闭。

こんにちは、@pq9420さん、タイトルが仕様に準拠していないため、ご提案いただいた問題はクローズされました。
