### ISSUE TITLE
[BUG] Final2x-core: not found

### ISSUE THREAD

**Issue by jinyun** [Tohrusky/Final2x#95]
### Describe the bug | 描述错误 | BUGの説明

```bash
// ...
/bin/sh: 1: /tmp/.mount_Final2jeBEwi/resources/app/resources/Final2x-core/Final2x-core: not found
CLOSE CODE:127
```

### To reproduce | 复现步骤 | 再現方法
1. 选择文件之后，点击开始处理文件，提示 处理失败，打开日志显示 Final2x-core: not found

### Context | 运行环境 | バックグラウンド
 - OS: Linux Mint 21.1
 - Arch: x64
 - Final2x version： v1.1.3 Final2x-linux-pip-x64-AppImage.AppImage

### Additional context | 附加内容 | 追加コンテキスト
Add any other context and screenshots to help explain your problem.

**Comment by Tohrusky** [comment]
https://final2x.tohru.top/pages/guide/install.html#linux

**Comment by Tohrusky** [comment]
用Mint的话，可以直接试试ubuntu版呀

**Comment by Tohrusky** [comment]
用Mint的话，可以直接试试ubuntu版呀

**Comment by Tohrusky** [comment]
Hello @d-blanken, your issue has been closed because it has been inactive for a long time.

你好 @d-blanken，你的 issue 因为长时间不活跃而被自动关闭。

こんにちは、@d-blankenさん、お問い合わせは長期間活動がないため、閉じられました。

**Comment by d-blanken** [comment]
Hello Tohrusky, I do not get what Your answer says and I do not know how to overcome my problem.
(I do not use Linux like mentioned above.)
In my log there is no close code 127, but I have close code 3221225477.
Any hint is wellcome.

**Comment by basilioss** [comment]
I have the same issue on Arch Linux
```
[{"label":"CPU: Ryzen 5 5500U with Radeon Graphics","value":-1},{"label":"GPU 0: Lucienne","value":0},{"label":"GPU: Auto","value":114514}]
{"gpuid":0,"inputpath":["/home/basilios/80a69adb9107316d20ccd3e64512b21b.jpg"],"model":"RealCUGAN-pro","modelscale":2,"modelnoise":0,"outputpath":"/home/basilios","targetscale":0,"tta":false}
/bin/sh: 1: /opt/final2x/final2x.asar/resources/Final2x-core/Final2x-core: not found
CLOSE CODE:127
```

**Comment by Tohrusky** [comment]
> I have the same issue on Arch Linux
> 
> ```
> [{"label":"CPU: Ryzen 5 5500U with Radeon Graphics","value":-1},{"label":"GPU 0: Lucienne","value":0},{"label":"GPU: Auto","value":114514}]
> {"gpuid":0,"inputpath":["/home/basilios/80a69adb9107316d20ccd3e64512b21b.jpg"],"model":"RealCUGAN-pro","modelscale":2,"modelnoise":0,"outputpath":"/home/basilios","targetscale":0,"tta":false}
> /bin/sh: 1: /opt/final2x/final2x.asar/resources/Final2x-core/Final2x-core: not found
> CLOSE CODE:127
> ```

https://final2x.tohru.top/pages/guide/install.html#linux
plz make sure that cli can work?

**Comment by basilioss** [comment]
I installed `final2x-bin` with [paru](https://github.com/Morganamilo/paru), by default pacman does not support installing packages from AUR. `Final2x-core --help` didn't work, it seems like it only installs final2x binary.
I tried to install `Final2x-core` with pip, but it gives this error:
```
$ pip install Final2x-core
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try 'pacman -S
    python-xyz', where xyz is the package you are trying to
    install.

    If you wish to install a non-Arch-packaged Python package,
    create a virtual environment using 'python -m venv path/to/venv'.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip.

    If you wish to install a non-Arch packaged Python application,
    it may be easiest to use 'pipx install xyz', which will manage a
    virtual environment for you. Make sure you have python-pipx
    installed via pacman.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```
I managed to install `Final2x-core` with pipx, but now I have this error:
```
...
ImportError: libomp.so.5: cannot open shared object file: No such file or directory
CLOSE CODE:1
```
Here's a full log: https://pastebin.com/raw/aLbTjSD8
As far as I understand, the `openmp` package provides `libomp`, but if I install it nothing changes.

**Comment by basilioss** [comment]
Creating a symbolic link resolved this issue:
```
cd /usr/lib
sudo ln -s libomp.so libomp.so.5
```

**Comment by Tohrusky** [comment]
Congrats! I'm very happy to see it working for linux users, which is why it was developed in the first place!

![ac50ddc7bc62dbf443d8f067517b6755.gif](https://github.com/Tohrusky/Final2x/assets/65994850/61afda1a-61ce-4ad2-80a2-6bfc561e7eca)

**Comment by alpharde** [comment]
I have the same problem with arch + appimage.
So the fix is "do not use the appimage"?
